### ISSUE TITLE
Code fails with some attempt to set mute

### ISSUE THREAD

**Issue by davidfavor** [wethegit/wtc-autoplay-video#1]
Reported error...

```
jquery-3.3.1.min.js:2 jQuery.Deferred exception: Cannot set property 'muted' of null TypeError: Cannot set property 'muted' of null
    at new AutoplayVideo (https://websitecheckertoolbox.com/video-test/wtc-autoplay-video.es5.js:345:24)
    at autoplay_video (https://websitecheckertoolbox.com/video-test/:25:8)
    at HTMLDocument.<anonymous> (https://websitecheckertoolbox.com/video-test/:31:5)
    at l (https://websitecheckertoolbox.com/video-test/jquery-3.3.1.min.js:2:29375)
    at c (https://websitecheckertoolbox.com/video-test/jquery-3.3.1.min.js:2:29677) undefined
```

HTML used...
```
<!DOCTYPE html>

<html lang="en">

<head>

 <meta charset="UTF-8">
 <title>Video Autoplay Test</title>

 <meta name="description" content="Video Autoplay Test">
 <meta name="author" content="David Favor">

 <script src="./jquery-3.3.1.min.js"></script>
 <script src="./wtc-autoplay-video.es5.js"></script>

 <script>

  function autoplay_video () {

     console.log("autoplay_video(): called");

     var videos = document.querySelectorAll('.autoplay-video');

     for (var i = 0; i < videos.length; i++) {
       new WTCAutoplayVideo.default(videos[i], { fullWidth: false, vpOn: 0 });
     }

  }

  $(document).ready(function() {
    autoplay_video();
  });

 </script>

</head>

<body>

<h1>Video Autoplay Test</h1>

<div data-controller="AutoplayVideo" class="autoplay-video">
 <video id="playme" width="1280" height="720" controls>
  <source src="https://davidfavor.com/videos/email/2018-12-22-recyled-spam-trap-example-and-fix.mp4" type="video/mp4">
  Your browser does not support the video tag.
 </video>
</div>

</body>

</html>
```

**Comment by liamegan** [comment]
You're trying to run the controller on the video itself, this class expects specific markup for the videos:
```
<div class="your-container-class">
  <video
    class="autoplay-video__video"
    autoplay
    playsinline
    muted
    loop
  >
    <source
      src="video.mp4"
      type="video/mp4"
    />
  </video>
  <!-- REQUIRED -->
  <img
    class="autoplay-video__fallback"
    src="fallback.png"
    alt="Fallback"
  />
  <!-- OPTIONAL -->
  <img
    class="autoplay-video__preloader"
    src="preloader.png"
    alt="Preloader"
  />
</div>
```

Where `your-container-class` is the element that you provide to the class.

Closing, not an issue.
